CREATE TABLE cliente(
   id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
       nome VARCHAR(100) NOT NULL,
       email VARCHAR(100) UNIQUE NOT NULL,
       telefone VARCHAR(20),
       senha VARCHAR(255) NOT NULL
   );
